name: xproject_generator
description: CLI and library to scaffold Flutter applications and feature modules using opinionated GetX and Riverpod templates.
version: 1.0.2
homepage: https://github.com/anonimeact/XProject-Generator
repository: https://github.com/anonimeact/XProject-Generator

environment:
  sdk: '>=3.10.0 <4.0.0'

executables:
  xproject: xproject

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  interact: ^2.2.0
  mason_logger: ^0.3.3
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6